"""Добавление модели Product

Revision ID: 3832a8cda4da
Revises: 1ce8ad3b652c
Create Date: 2026-01-18 13:35:42.280867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3832a8cda4da'
down_revision = '1ce8ad3b652c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_weight_based', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_weight', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Integer(), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('is_discounted', sa.Boolean(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('tags', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
