"""remove min/max weight from product

Revision ID: 5c7287bc8a29
Revises: 8477ee04eaed
Create Date: 2026-01-26 19:37:58.525621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7287bc8a29'
down_revision = '8477ee04eaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('products', schema=None) as batch_op:
        # ✅ ВАЖНО: server_default чтобы не упасть на существующих строках
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=False, server_default='7'))
        batch_op.drop_column('min_weight')
        batch_op.drop_column('max_weight')

    # ✅ на всякий случай добьём NULL (если вдруг где-то появилось)
    op.execute("UPDATE products SET shelf_life_days = 7 WHERE shelf_life_days IS NULL;")

    # ✅ (опционально) убираем дефолт из БД, оставляем дефолт в модели
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('shelf_life_days', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_weight', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('min_weight', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('shelf_life_days')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))

    op.drop_table('batches')
    # ### end Alembic commands ###
